import{S as f,a as m,i as s}from"./assets/vendor-GN5hr8qZ.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();const c=document.querySelector(".gallery"),u=document.querySelector("#loader");let p=new f(".gallery a",{sourceAttr:"href",captionsData:"alt",overlayOpacity:.8,captionDelay:250,className:"lightbox"});function g(a){c.innerHTML=a.map(({webformatURL:r,largeImageURL:o,tags:i,likes:e,views:t,comments:n,downloads:d})=>`<li class="gallery-item">
    <a class="gallery-link" href="${o}">
    <img class="gallery-image" src="${r}" alt="${i}"/>
    </a>
    <div class="card-info">
    <p>${e}</p>
    <p>${t}</p>
    <p>${n}</p>
    <p>${d}</p></div>
    </li>`).join(" "),p.refresh()}function y(){c.innerHTML=""}function h(){u.classList.remove("hidden")}function l(){u.classList.add("hidden")}const L="52855344-2930eb43dc046f1677ebd214e";function b(a){return m("https://pixabay.com/api/",{params:{key:L,q:a,image_type:"photo",orientation:"horizontal",safesearch:!0}}).then(r=>r.data.hits)}const v=document.querySelector(".form"),w=document.querySelector('input[name="search-text"]');v.addEventListener("submit",S);l();function S(a){a.preventDefault(),h(),y();const r=w.value.trim().toLowerCase();if(!r){s.warning({title:"Caution",message:"Please select at least one item.",color:"yellow",position:"topRight"}),l();return}b(r).then(o=>{let i=o.filter(e=>e.tags.toLowerCase().split(", ").includes(r));if(i.length===0){s.warning({title:"Caution",message:"Sorry, there are no images matching your search query. Please, try again!",color:"red",position:"topRight"});return}g(i)}).catch(o=>s.warning({title:"Caution",message:o.message,color:"red",position:"topRight"})).finally(()=>{l()})}
//# sourceMappingURL=index.js.map
